import type { HeroArchetypeEntity, MarketplaceHeroArchetype } from "./types";

const ALL: MarketplaceHeroArchetype[] = [
  "premium_cinematic",
  "luxury_minimal",
  "dark_brutal",
  "clean_marketplace",
  "emotional_lifestyle",
  "gift_oriented",
  "anime_heavy",
  "mass_market_bright",
  "hyper_commercial",
  "experimental",
];

/** Keyword hints matched against pasted SERP row text (manual, human labels). */
export const HERO_ARCHETYPE_CATALOG: readonly HeroArchetypeEntity[] = [
  {
    id: "premium_cinematic",
    archetype: "premium_cinematic",
    description: "Campaign shadows, controlled motion cues, editorial premium without runway excess.",
    dominantPatterns: ["cinematic", "shadow", "editorial", "film", "noir", "кинема", "тень", "премиум кадр"],
    dominantColors: ["black", "charcoal", "navy", "washed", "черн", "графит", "темн"],
    modelUsage: "Often model-led with deliberate pose, not packshot-only.",
    printStyle: "Print secondary to silhouette; hierarchy preserved at thumbnail scale.",
    readabilityBias: "mid",
    premiumSignal: "high",
    saturationRisk: "Medium in fashion corridors; spikes when many brands copy shadow-stack.",
    emotionalTone: "Confident, restrained drama.",
    marketplaceFit: "Strong on WB/Ozon when print remains legible in miniatures.",
    recommendedUse: "Differentiate from flat white-background mass when field is muddy.",
    dangerZones: ["Illegible print", "Fake HDR", "Over-editorial runway framing"],
  },
  {
    id: "luxury_minimal",
    archetype: "luxury_minimal",
    description: "Quiet luxury surfaces, generous negative space, material truth.",
    dominantPatterns: ["minimal", "quiet", "negative space", "linen", "stone", "минимал", "тишина", "простор"],
    dominantColors: ["white", "bone", "sand", "greige", "бел", "крем", "натурал"],
    modelUsage: "Optional model; often still-life discipline.",
    printStyle: "Small restrained print; premium via spacing and texture.",
    readabilityBias: "high",
    premiumSignal: "high",
    saturationRisk: "Low–mid; overlaps when everyone uses identical white void.",
    emotionalTone: "Calm authority.",
    marketplaceFit: "Excellent readability; watch sameness vs competitors.",
    recommendedUse: "Premium proof without loud graphics.",
    dangerZones: ["Sterile sameness", "Tiny illegible SKU cues"],
  },
  {
    id: "dark_brutal",
    archetype: "dark_brutal",
    description: "Hard contrast, industrial shadows, aggressive silhouette clarity.",
    dominantPatterns: ["brutal", "concrete", "industrial", "mono", "hard light", "брутал", "жест", "контраст"],
    dominantColors: ["black", "mono", "graphite", "асфальт", "моно"],
    modelUsage: "Model optional; graphic strength carries frame.",
    printStyle: "High-contrast print blocks; must stay legible at thumb scale.",
    readabilityBias: "mid",
    premiumSignal: "mid",
    saturationRisk: "High when corridor clusters on dark stacks.",
    emotionalTone: "Cold precision.",
    marketplaceFit: "Strong cut-through until field saturates on darkness.",
    recommendedUse: "Controlled accents vs mass dark clones.",
    dangerZones: ["Unreadable black-on-black", "Muddy print", "Same pose cluster"],
  },
  {
    id: "clean_marketplace",
    archetype: "clean_marketplace",
    description: "Bright studio clarity, packshot discipline, SKU-first framing.",
    dominantPatterns: ["packshot", "studio", "white bg", "flat", "frontal", "студи", "белый фон", "пакшот"],
    dominantColors: ["white", "light grey", "белый", "светл"],
    modelUsage: "Frequent straight-on model or flat lay.",
    printStyle: "Print-forward; SKU legibility priority.",
    readabilityBias: "high",
    premiumSignal: "mid",
    saturationRisk: "Very high — default marketplace gravity.",
    emotionalTone: "Functional trust.",
    marketplaceFit: "Maximum compatibility; hardest to differentiate.",
    recommendedUse: "Baseline hygiene; pair with print or material proof.",
    dangerZones: ["Generic frontal wall", "Banner clutter", "Price-only differentiation"],
  },
  {
    id: "emotional_lifestyle",
    archetype: "emotional_lifestyle",
    description: "Warm lifestyle context, human proximity, story-led framing.",
    dominantPatterns: ["lifestyle", "street", "cafe", "home", "лук", "улиц", "будни", "эмоц"],
    dominantColors: ["warm", "earth", "sun", "тепл", "закат"],
    modelUsage: "Model-forward with environment storytelling.",
    printStyle: "Print competes with scene — needs hierarchy discipline.",
    readabilityBias: "low",
    premiumSignal: "mid",
    saturationRisk: "Mid; overlaps when scenes feel stock.",
    emotionalTone: "Relatable aspiration.",
    marketplaceFit: "Good for emotional categories; watch thumbnail clutter.",
    recommendedUse: "Differentiate with authentic scene specificity.",
    dangerZones: ["Busy backgrounds", "Lost print", "Stock-photo sameness"],
  },
  {
    id: "gift_oriented",
    archetype: "gift_oriented",
    description: "Ribbon cues, occasion framing, bundle/gift semantics.",
    dominantPatterns: ["gift", "box", "ribbon", "подар", "8 марта", "23 февр", "набор"],
    dominantColors: ["red", "gold", "pastel", "красн", "золот"],
    modelUsage: "Often product-only with festive props.",
    printStyle: "Occasion-led copy zones; print can be busy.",
    readabilityBias: "mid",
    premiumSignal: "low",
    saturationRisk: "Seasonal spikes; noisy overlap near holidays.",
    emotionalTone: "Festive urgency.",
    marketplaceFit: "High conversion language risk; clarity still mandatory.",
    recommendedUse: "Seasonal capsules; avoid year-round gift noise.",
    dangerZones: ["Unreadable promo stacks", "Tacky clip-art"],
  },
  {
    id: "anime_heavy",
    archetype: "anime_heavy",
    description: "Illustration-forward, kawaii/street anime cues, graphic maximalism.",
    dominantPatterns: ["anime", "kawaii", "manga", "иллюстр", "аниме", "кавай"],
    dominantColors: ["neon", "pastel pop", "violet", "роз", "неон"],
    modelUsage: "Mixed; sometimes character-led.",
    printStyle: "Graphic-heavy; readability varies.",
    readabilityBias: "low",
    premiumSignal: "low",
    saturationRisk: "Niche pockets; overlap inside niche is violent.",
    emotionalTone: "Playful hype.",
    marketplaceFit: "Category-specific; keep SKU anchor visible.",
    recommendedUse: "Own niche lane; avoid blending with adjacent graphic brands.",
    dangerZones: ["Print lost in illustration", "Childish premium mismatch"],
  },
  {
    id: "mass_market_bright",
    archetype: "mass_market_bright",
    description: "High-key brightness, promo cues, loud color blocks.",
    dominantPatterns: ["sale", "discount", "bright", "pop", "акци", "скид", "ярк", "неон баннер"],
    dominantColors: ["yellow", "red", "neon", "желт", "ярк"],
    modelUsage: "Variable; often product-first with stickers.",
    printStyle: "Promo-forward; hierarchy fights price badges.",
    readabilityBias: "mid",
    premiumSignal: "low",
    saturationRisk: "Extreme in crowded corridors.",
    emotionalTone: "Urgent bargain energy.",
    marketplaceFit: "Works for volume; toxic for premium corridors.",
    recommendedUse: "Avoid for premium proof; useful as contrast diagnosis.",
    dangerZones: ["Cheapness signal", "Thumbnail noise", "Trust erosion"],
  },
  {
    id: "hyper_commercial",
    archetype: "hyper_commercial",
    description: "Sticker stacks, badges, multi-offer framing, aggressive USPs.",
    dominantPatterns: ["badge", "sticker", "x2", "bundle", "badge stack", "наклей", "комплект", "хит"],
    dominantColors: ["multi", "rainbow", "mixed", "микс"],
    modelUsage: "Low; UI chrome dominates.",
    printStyle: "Typography war; print often secondary.",
    readabilityBias: "low",
    premiumSignal: "low",
    saturationRisk: "High wherever promos cluster.",
    emotionalTone: "Loud utility.",
    marketplaceFit: "Conversion-first; brand equity risk.",
    recommendedUse: "Diagnose overcrowding; strip for premium lanes.",
    dangerZones: ["Unreadable hero", "Trust collapse on premium SKUs"],
  },
  {
    id: "experimental",
    archetype: "experimental",
    description: "Odd angles, collage, glitch, avant framing — high variance.",
    dominantPatterns: ["collage", "glitch", "weird angle", "abstract", "эксперим", "коллаж", "глич"],
    dominantColors: ["mixed", "acid", "split", "микс"],
    modelUsage: "Unpredictable.",
    printStyle: "Unstable hierarchy — readability risk.",
    readabilityBias: "low",
    premiumSignal: "mid",
    saturationRisk: "Low share but high adjacent overlap when trendy.",
    emotionalTone: "Provocation / novelty.",
    marketplaceFit: "Rare; test carefully on thumbnails.",
    recommendedUse: "Surgical tests, not default shelf language.",
    dangerZones: ["SKU invisibility", "Niche-only comprehension"],
  },
];

export function catalogByArchetype(): Map<MarketplaceHeroArchetype, HeroArchetypeEntity> {
  const m = new Map<MarketplaceHeroArchetype, HeroArchetypeEntity>();
  for (const e of HERO_ARCHETYPE_CATALOG) m.set(e.archetype, e);
  return m;
}

export function allArchetypeIds(): readonly MarketplaceHeroArchetype[] {
  return ALL;
}
