import type { CommandCenterReport } from "./types";

function bullets(title: string, items: string[]) {
  if (!items.length) return "";
  return `### ${title}\n${items.map((x) => `- ${x}`).join("\n")}\n\n`;
}

export function strategicCommandToMarkdown(r: CommandCenterReport): string {
  const ev = r.executiveVerdict;
  const dash = r.executiveDashboard;
  const sc = r.unifiedScores;
  const lines: string[] = [
    "# VOKRA · Strategic Command Center",
    "",
    `> schema v${r.schemaVersion}`,
    "",
    "## Executive verdict",
    `- **Verdict:** ${ev.verdict}`,
    `- **Confidence:** ${ev.confidence}`,
    `- **Domination score:** ${ev.dominationScore}`,
    `- **Market window:** ${ev.marketWindow}`,
    `- **Primary risk:** ${ev.primaryRisk}`,
    `- **Why now:** ${ev.whyNow}`,
    "",
    "## Executive dashboard",
    `**Command summary:** ${dash.commandSummary}`,
    `**Market pressure:** ${dash.marketPressure}`,
    `**Launch priority:** ${dash.launchPriority}`,
    `**Profitability potential:** ${dash.profitabilityPotential}`,
    "",
    bullets("Recommended actions", dash.recommendedActions),
    "## Unified scores (0–100)",
    `- **Opportunity:** ${sc.opportunity}`,
    `- **Launch readiness:** ${sc.launchReadiness}`,
    `- **Profitability:** ${sc.profitability}`,
    `- **Visual cohesion:** ${sc.visualCohesion}`,
    `- **SEO leverage:** ${sc.seoLeverage}`,
    `- **Production risk (higher = riskier):** ${sc.productionRisk}`,
    "",
    "## Trend signal brief (meta read)",
    `### ${r.trendSignalBrief.headline}`,
    r.trendSignalBrief.synthesis,
    "",
    bullets("Emotional drivers", r.trendSignalBrief.emotionalDrivers),
    `- Saturation: ${r.trendSignalBrief.saturation}`,
    `- Velocity: ${r.trendSignalBrief.velocity}`,
    "",
    "## Competitor synthesis",
    r.competitorSynthesis.narrative,
    "",
    bullets("Market weaknesses", r.competitorSynthesis.marketWeaknesses),
    bullets("Visual patterns", r.competitorSynthesis.visualPatterns),
    bullets("SEO patterns", r.competitorSynthesis.seoPatterns),
    bullets("Pricing patterns", r.competitorSynthesis.pricingPatterns),
    "## SKU launch map",
    ...r.skuLaunchMap.map(
      (row) =>
        `### ${row.skuName} (P${row.priority}, ${row.fitLine})\n${row.rationale}\n**MP angle:** ${row.marketplaceAngle}\n`,
    ),
    "## Pricing strategy",
    `**Anchor band:** ${r.pricingStrategy.anchorBand}`,
    `**WB / Ozon tactics:** ${r.pricingStrategy.wbOzonTactics}`,
    "",
    bullets("Price ladder", r.pricingStrategy.ladder),
    bullets("Margin guardrails", r.pricingStrategy.marginGuardrails),
    "## Visual direction",
    `**Hero:** ${r.visualDirection.heroStyle}`,
    `**Color:** ${r.visualDirection.colorDirection}`,
    `**Composition:** ${r.visualDirection.compositionDirection}`,
    `**Photography:** ${r.visualDirection.photographyDirection}`,
    `**Oversize:** ${r.visualDirection.oversizeNotes}`,
    `**Standard fit:** ${r.visualDirection.standardFitNotes}`,
    "",
    bullets("CTR / PDP", r.visualDirection.marketplaceCtrAdvice),
    "## Content strategy",
    bullets("Pillars", r.contentStrategy.pillars),
    bullets("Reels", r.contentStrategy.reelsIdeas),
    bullets("Campaigns", r.contentStrategy.campaignAngles),
    bullets("UGC", r.contentStrategy.ugcHooks),
    bullets("Story", r.contentStrategy.storytellingAngles),
    "## Production risk (DTF-first)",
    `- **DTF pipeline:** ${r.productionRiskAnalysis.dtfPipeline}`,
    `- **Complexity:** ${r.productionRiskAnalysis.complexity}`,
    `- **Scalability:** ${r.productionRiskAnalysis.scalability}`,
    `- **Risk:** ${r.productionRiskAnalysis.riskLevel}`,
    `- **Margin:** ${r.productionRiskAnalysis.marginPotential}`,
    "",
    bullets("Bottlenecks", r.productionRiskAnalysis.bottlenecks),
    bullets("Mitigations", r.productionRiskAnalysis.mitigations),
    bullets("Manufacturing", r.productionRiskAnalysis.manufacturingAdvice),
    "## SEO priority map",
    ...r.seoPriorityMap.flatMap((tier) => [
      `### ${tier.tier}`,
      ...tier.items.map((it) => `- **${it.focus}** (${it.priority}): ${it.action}`),
      "",
    ]),
    "## Action horizons",
    bullets("Next 7 days", r.actionHorizons.days7),
    bullets("Next 30 days", r.actionHorizons.days30),
    bullets("Next 90 days", r.actionHorizons.days90),
    "## 7-day tactical grid",
    `**Day 1:** ${r.launchPlanWeek.day1}`,
    `**Day 2:** ${r.launchPlanWeek.day2}`,
    `**Day 3:** ${r.launchPlanWeek.day3}`,
    `**Day 4:** ${r.launchPlanWeek.day4}`,
    `**Day 5:** ${r.launchPlanWeek.day5}`,
    `**Day 6:** ${r.launchPlanWeek.day6}`,
    `**Day 7:** ${r.launchPlanWeek.day7}`,
    "",
    bullets("Launch recommendations", r.launchRecommendations),
    bullets("Bottleneck detection", r.bottleneckDetection),
    bullets("Recommended experiments", r.recommendedExperiments),
    bullets("Scaling opportunities", r.scalingOpportunities),
    "## Growth forecast",
    r.growthForecast,
    "",
    "## Tactical roadmap",
    r.tacticalRoadmap,
    "",
    "## AI departments",
  ];

  for (const a of r.aiDepartments) {
    lines.push(
      `### ${a.role} · ${a.department}`,
      `- Status: ${a.status}`,
      `- Mission: ${a.mission}`,
      `- Coordination: ${a.coordination}`,
      "",
      a.output,
      "",
    );
  }

  lines.push("## Final command", "", r.finalCommand, "");
  return lines.join("\n");
}
