import type { GuidedSetupStepId, GuidedSetupStepMeta } from "./types";

export const GUIDED_SETUP_STEPS: Record<GuidedSetupStepId, GuidedSetupStepMeta> = {
  import_data: {
    id: "import_data",
    navId: "dataImport",
    titleKey: "gsp.step.import_data.title",
    whyKey: "gsp.step.import_data.why",
    whatKey: "gsp.step.import_data.what",
    outcomeKey: "gsp.step.import_data.outcome",
  },
  activate_snapshot: {
    id: "activate_snapshot",
    navId: "entityFusion",
    titleKey: "gsp.step.activate_snapshot.title",
    whyKey: "gsp.step.activate_snapshot.why",
    whatKey: "gsp.step.activate_snapshot.what",
    outcomeKey: "gsp.step.activate_snapshot.outcome",
  },
  cleanup_data: {
    id: "cleanup_data",
    navId: "dataCleanup",
    titleKey: "gsp.step.cleanup_data.title",
    whyKey: "gsp.step.cleanup_data.why",
    whatKey: "gsp.step.cleanup_data.what",
    outcomeKey: "gsp.step.cleanup_data.outcome",
  },
  unit_economics: {
    id: "unit_economics",
    navId: "unitEconomics",
    titleKey: "gsp.step.unit_economics.title",
    whyKey: "gsp.step.unit_economics.why",
    whatKey: "gsp.step.unit_economics.what",
    outcomeKey: "gsp.step.unit_economics.outcome",
  },
  assortment_actions: {
    id: "assortment_actions",
    navId: "assortmentActions",
    titleKey: "gsp.step.assortment_actions.title",
    whyKey: "gsp.step.assortment_actions.why",
    whatKey: "gsp.step.assortment_actions.what",
    outcomeKey: "gsp.step.assortment_actions.outcome",
  },
  execution_plan: {
    id: "execution_plan",
    navId: "assortmentActions",
    titleKey: "gsp.step.execution_plan.title",
    whyKey: "gsp.step.execution_plan.why",
    whatKey: "gsp.step.execution_plan.what",
    outcomeKey: "gsp.step.execution_plan.outcome",
  },
  hero_competitor_analysis: {
    id: "hero_competitor_analysis",
    navId: "competitiveMap",
    titleKey: "gsp.step.hero_competitor_analysis.title",
    whyKey: "gsp.step.hero_competitor_analysis.why",
    whatKey: "gsp.step.hero_competitor_analysis.what",
    outcomeKey: "gsp.step.hero_competitor_analysis.outcome",
  },
  founder_brief: {
    id: "founder_brief",
    navId: "founderBrief",
    titleKey: "gsp.step.founder_brief.title",
    whyKey: "gsp.step.founder_brief.why",
    whatKey: "gsp.step.founder_brief.what",
    outcomeKey: "gsp.step.founder_brief.outcome",
  },
  control_tower: {
    id: "control_tower",
    navId: "controlTower",
    titleKey: "gsp.step.control_tower.title",
    whyKey: "gsp.step.control_tower.why",
    whatKey: "gsp.step.control_tower.what",
    outcomeKey: "gsp.step.control_tower.outcome",
  },
};
