import type { CardProductionPlan } from "./types";

export function planToMarkdownBrief(plan: CardProductionPlan): string {
  const c = plan.readinessChecks;
  const cc = plan.contentReadinessChecks;
  const lines: string[] = [
    `# ${plan.cardTitle}`,
    "",
    `**Marketplace:** ${plan.marketplace} · **Card status:** ${plan.cardStatus}`,
    "",
    "## WB title",
    plan.wbTitle.trim() || "—",
    "",
    "## Ozon title",
    plan.ozonTitle.trim() || "—",
    "",
    "## Primary keywords",
    plan.primaryKeywords.length ? plan.primaryKeywords.map((k) => `- ${k}`).join("\n") : "—",
    "",
    "## Secondary keywords",
    plan.secondaryKeywords.length ? plan.secondaryKeywords.map((k) => `- ${k}`).join("\n") : "—",
    "",
    "## Description draft",
    plan.descriptionDraft.trim() || "—",
    "",
    "## Rich content blocks",
    ...plan.richContentBlocks.map((b) => `### ${b.headline}\n${b.body}\n`),
    "## Material",
    plan.materialBlock.trim() || "—",
    "",
    "## Print quality",
    plan.printQualityBlock.trim() || "—",
    "",
    "## Care",
    plan.careInstructions.trim() || "—",
    "",
    "## Size grid note",
    plan.sizeBlock.trim() || "—",
    "",
    "## SEO cluster (source)",
    plan.seoCluster.trim() || "—",
    "",
    "## Marketplace notes",
    plan.marketplaceNotes.trim() || "—",
    "",
    "## Production notes",
    plan.productionNotes.trim() || "—",
    "",
    "## Visual readiness",
    `- hero: ${c.heroVisualReady} · support: ${c.supportVisualsReady} · detail: ${c.detailShotsReady}`,
    `- SEO cluster field: ${c.seoReady} · size grid visual: ${c.sizeGridReady}`,
    `- clarity: ${c.marketplaceClarityReady} · brand: ${c.brandFitReady}`,
    "",
    "## Content readiness",
    `- SEO pack: ${cc.seoContentReady} · description: ${cc.descriptionContentReady} · rich: ${cc.richContentStructureReady}`,
    `- material: ${cc.materialBlockReady} · size note: ${cc.sizeBlockReady} · marketplace copy: ${cc.marketplaceCopyReady}`,
    "",
    "## SEO / content warnings",
    plan.seoWarnings.length ? plan.seoWarnings.map((w) => `- ${w}`).join("\n") : "—",
    "",
    "## Risk / blockers",
    plan.blockers.length ? plan.blockers.map((b) => `- ${b}`).join("\n") : "—",
    "",
    "## Visual asset ids",
    `- hero: ${plan.heroVisualId ?? "—"}`,
    `- support: ${plan.supportVisualIds.join(", ") || "—"}`,
    `- detail: ${plan.detailVisualIds.join(", ") || "—"}`,
    `- rich: ${plan.richContentVisualIds.join(", ") || "—"}`,
    `- grid: ${plan.sizeGridVisualId ?? "—"}`,
    "",
    "## Future core ids",
    `- skuIds: ${plan.skuIds.join(", ") || "—"}`,
    `- cardIds: ${plan.cardIds.join(", ") || "—"}`,
    `- wbArticle: ${plan.wbArticle ?? "—"} · ozonOfferId: ${plan.ozonOfferId ?? "—"}`,
  ];
  return lines.join("\n");
}

export function planToJsonString(plan: CardProductionPlan): string {
  return JSON.stringify(plan, null, 2);
}
