import type { HeroPostLaunchObservation } from "./types";

export function heroPostLaunchObservationToPlainText(obs: HeroPostLaunchObservation): string {
  const lines = [
    `Post-Launch Observation · ${obs.query} · ${obs.marketplace}`,
    `Launch: ${obs.launchDate || "—"} · Observed: ${obs.observationDate || "—"} · Window: ${obs.observationWindowDays}d`,
    `Launch package: ${obs.sourceLaunchPackageId}`,
    "",
    "## Marketplace observations",
    `Ranking: ${obs.rankingObservation || "—"}`,
    `Competitors: ${obs.competitorMovement || "—"}`,
    `Readability: ${obs.readabilityObservation || "—"}`,
    `Fatigue: ${obs.fatigueObservation || "—"}`,
    `Premium perception: ${obs.premiumPerceptionObservation || "—"}`,
    `Customer signals: ${obs.customerSignalObservation || "—"}`,
    `Operational issues: ${obs.operationalIssues || "—"}`,
    "",
    "## Assessment",
    `Suspected outcome: ${obs.suspectedOutcome || "—"}`,
    `Next recommendation: ${obs.nextRecommendation || "—"}`,
    `Refresh risk: ${obs.refreshRisk || "—"}`,
    "",
    "## Learning reinforcement (heuristic)",
    ...obs.learningReinforcement.map((x) => `- ${x}`),
    "",
    "## Notes",
    obs.notes || "—",
    "",
    "_Manual operator observations only — no API metrics, no CTR claims._",
  ];
  return lines.join("\n");
}

export function heroPostLaunchObservationToMarkdown(obs: HeroPostLaunchObservation): string {
  const esc = (s: string) => s.replace(/\|/g, "\\|");
  return [
    `# Post-Launch Observation`,
    ``,
    `**Query:** ${esc(obs.query)}  `,
    `**Marketplace:** ${esc(obs.marketplace)}  `,
    `**Launch date:** ${obs.launchDate || "—"}  `,
    `**Observation date:** ${obs.observationDate || "—"}  `,
    `**Window:** ${obs.observationWindowDays} days  `,
    `**Launch package:** \`${obs.sourceLaunchPackageId}\`  `,
    ``,
    `## Timing`,
    `Operator-recorded launch and observation window — not synced from WB/Ozon APIs.`,
    ``,
    `## Marketplace observations`,
    `| Signal | Observation |`,
    `| --- | --- |`,
    `| Ranking | ${esc(obs.rankingObservation || "—")} |`,
    `| Competitor movement | ${esc(obs.competitorMovement || "—")} |`,
    `| Readability | ${esc(obs.readabilityObservation || "—")} |`,
    `| Fatigue | ${esc(obs.fatigueObservation || "—")} |`,
    `| Premium perception | ${esc(obs.premiumPerceptionObservation || "—")} |`,
    `| Customer signals | ${esc(obs.customerSignalObservation || "—")} |`,
    `| Operational issues | ${esc(obs.operationalIssues || "—")} |`,
    ``,
    `## Assessment`,
    `**Suspected outcome:** ${obs.suspectedOutcome || "—"}  `,
    `**Next recommendation:** ${obs.nextRecommendation || "—"}  `,
    `**Refresh risk:** ${obs.refreshRisk || "—"}  `,
    ``,
    `## Learning reinforcement`,
    ...obs.learningReinforcement.map((x) => `- ${x}`),
    ``,
    `## Notes`,
    obs.notes || "—",
    ``,
    `---`,
    `_Manual marketplace learning journal — transparent heuristics only._`,
  ].join("\n");
}
