import type { CollectionEntity } from "./types";

function bullets(title: string, items: readonly string[]): string {
  if (!items.length) return "";
  return `${title}\n${items.map((x) => `- ${x}`).join("\n")}\n\n`;
}

export function collectionEntityToMarkdown(entity: CollectionEntity): string {
  const v = entity.visualDirection;
  const s = entity.seoPlan;
  const l = entity.launchPlan;
  const p = entity.productionFit;

  return [
    `# ${entity.name}`,
    ``,
    `**ID:** ${entity.id} · **Pulse:** ${entity.pulseSeed} · **Kind:** ${entity.kind} · **Strategic role:** ${entity.strategicRole}`,
    ``,
    `## Best collection opportunity now`,
    entity.opportunityReason,
    ``,
    `## Collection concept`,
    entity.concept,
    ``,
    `**Corridor:** ${entity.corridorId} (${entity.corridorNameKey}) · pressure ${(entity.corridorPressure01 * 100).toFixed(0)}%`,
    ``,
    `**Target buyer:** ${entity.targetBuyer}`,
    `**Season / timing:** ${entity.seasonTiming}`,
    `**Brand fit:** ${entity.brandFit}`,
    `**Marketplace fit:** ${entity.marketplaceFit}`,
    `**Expected impact:** ${entity.expectedImpact}`,
    ``,
    `## Hero SKU structure`,
    ...entity.heroProducts.map((h) => `- **${h.title}** — ${h.note}`),
    ``,
    `## Support & cluster SKU structure`,
    ...entity.skuClusters.map((c) => `- **${c.label} (${c.role}) ×${c.count}** — ${c.note}`),
    `**SKU count target:** ${entity.skuCountTarget.min}–${entity.skuCountTarget.max}`,
    ``,
    `## Print family direction`,
    v.printDirection,
    bullets("Forbidden patterns", v.forbiddenPatterns),
    `## Visual direction`,
    `**Mood:** ${v.mood}`,
    `**Hero card:** ${v.heroCardDirection}`,
    `**Model / background:** ${v.modelBackgroundStyle}`,
    `**Main photo logic:** ${v.marketplaceMainPhotoLogic}`,
    `**Reels:** ${v.reelsDirection}`,
    ``,
    `## SEO cluster plan`,
    `**Primary:** ${s.primaryCluster}`,
    bullets("Secondary clusters", s.secondaryClusters),
    bullets("Forbidden semantic drift", s.forbiddenSemanticDrift),
    `**Title tone:** ${s.titleTone}`,
    `**Rich content angle:** ${s.richContentAngle}`,
    `**WB vs Ozon:** ${s.wbVsOzon}`,
    ``,
    `## Launch sequence`,
    `**Test wave:** ${l.testWave}`,
    `**Refresh wave:** ${l.refreshWave}`,
    `**Amplification:** ${l.amplificationWave}`,
    `**FBO wave:** ${l.fboWave}`,
    `**Hold / stop:** ${l.holdStopCondition}`,
    `**Order:** ${l.launchOrder}`,
    `**Do not launch:** ${l.doNotLaunch}`,
    ``,
    `## Production fit (DTF-first)`,
    `- DTF suitability: ${p.dtfSuitability}`,
    `- Print complexity: ${p.printComplexity}`,
    `- SKU complexity: ${p.skuComplexity}`,
    `- Packaging: ${p.packagingPressure}`,
    `- FBO prep: ${p.fboPrepPressure}`,
    `- Launch speed: ${p.launchSpeed}`,
    `- Production risk: ${p.productionRisk}`,
    p.operationalWarning ? `\n**⚠ Operational warning:** ${p.operationalWarning}\n` : "",
    `## Risk / stop conditions`,
    entity.risk,
    bullets("Stop conditions", entity.stopConditions),
    `## OS integration`,
    `- Executive next: ${entity.integration.executiveBestNext}`,
    `- Orchestrator route: ${entity.integration.primaryRouteId} (${entity.integration.primaryRouteKind})`,
    `- Objective: ${entity.integration.orchestratorObjective}`,
    `- ${entity.integration.signalFabricNote}`,
    `- ${entity.integration.temporalNote}`,
    `- Dominant cluster: ${entity.integration.dominantCluster}`,
    `- ${entity.integration.brandDnaGovernance}`,
    ``,
  ].join("\n");
}
