import type { HeroBattlePlan } from "./types";

export function heroBattlePlanToPlainText(plan: HeroBattlePlan): string {
  const lines = [
    `Hero Battle Plan · ${plan.query} · ${plan.marketplace}`,
    `Created: ${new Date(plan.createdAt).toISOString()}`,
    "",
    "## Battlefield",
    plan.competitorFieldSummary,
    "",
    "## Our diagnosis",
    plan.ourHeroDiagnosis,
    "",
    "## Biggest weakness",
    plan.biggestWeakness,
    "",
    "## Strongest advantage",
    plan.strongestAdvantage,
    "",
    "## Recommended direction",
    plan.recommendedArchetype,
    "",
    "## Readability directive",
    plan.readabilityDirective,
    "",
    "## Fatigue directive",
    plan.fatigueDirective,
    "",
    "## Refresh strategy",
    plan.refreshStrategy,
    "",
    "## Prompt direction",
    plan.promptDirection,
    "",
    "## Negative constraints",
    plan.negativeConstraints,
    "",
    "## Next actions",
    ...plan.nextActions.map((a, i) => `${i + 1}. ${a}`),
    "",
    "## Risks",
    ...plan.riskFlags.map((a, i) => `${i + 1}. ${a}`),
    "",
    "## Confidence",
    plan.confidenceNote,
  ];
  return lines.join("\n");
}

export function heroBattlePlanToMarkdown(plan: HeroBattlePlan): string {
  const esc = (s: string) => s.replace(/\|/g, "\\|");
  const md = [
    `# Hero Battle Plan`,
    ``,
    `**Query:** ${esc(plan.query)}  `,
    `**Marketplace:** ${esc(plan.marketplace)}  `,
    `**Sources:** SERP \`${plan.sourceSerpSnapshotId}\`${plan.sourceOurCardSnapshotId ? ` · our card \`${plan.sourceOurCardSnapshotId}\`` : ""}  `,
    ``,
    `## Battlefield summary`,
    plan.competitorFieldSummary,
    ``,
    `## Our hero diagnosis`,
    plan.ourHeroDiagnosis,
    ``,
    `## Biggest weakness`,
    plan.biggestWeakness,
    ``,
    `## Strongest advantage`,
    plan.strongestAdvantage,
    ``,
    `## Recommended direction (archetype / lane)`,
    plan.recommendedArchetype,
    ``,
    `## Readability directive`,
    plan.readabilityDirective,
    ``,
    `## Fatigue directive`,
    plan.fatigueDirective,
    ``,
    `## Refresh strategy`,
    plan.refreshStrategy,
    ``,
    `## Prompt direction`,
    plan.promptDirection,
    ``,
    `## Negative constraints`,
    plan.negativeConstraints,
    ``,
    `## Next actions`,
    ...plan.nextActions.map((x) => `- ${x}`),
    ``,
    `## Risk flags`,
    ...plan.riskFlags.map((x) => `- ${x}`),
    ``,
    `## Confidence`,
    plan.confidenceNote,
    ``,
    `---`,
    `_Manual SERP + OS heuristics only — no scraping, no image AI, no CTR claims._`,
  ];
  return md.join("\n");
}
