import type { MarketplaceDataDomain } from "./types";

export const MARKETPLACE_DATA_DOMAINS: readonly MarketplaceDataDomain[] = [
  {
    id: "products",
    sourceOfTruth: "shared",
    syncDirection: "bidirectional",
    syncRisk: "high",
    operationalImportance: "critical",
    overwriteRulesKey: "iready.overwrite.products",
    navHint: "skuIntelligence",
  },
  {
    id: "skus",
    sourceOfTruth: "os_manual",
    syncDirection: "marketplace_to_os",
    syncRisk: "medium",
    operationalImportance: "critical",
    overwriteRulesKey: "iready.overwrite.skus",
    navHint: "skuIntelligence",
  },
  {
    id: "orders",
    sourceOfTruth: "marketplace_api",
    syncDirection: "marketplace_to_os",
    syncRisk: "low",
    operationalImportance: "medium",
    overwriteRulesKey: "iready.overwrite.orders",
  },
  {
    id: "stocks",
    sourceOfTruth: "shared",
    syncDirection: "bidirectional",
    syncRisk: "critical",
    operationalImportance: "critical",
    overwriteRulesKey: "iready.overwrite.stocks",
    navHint: "productionPressure",
  },
  {
    id: "warehouses",
    sourceOfTruth: "marketplace_api",
    syncDirection: "marketplace_to_os",
    syncRisk: "medium",
    operationalImportance: "high",
    overwriteRulesKey: "iready.overwrite.warehouses",
    navHint: "fboFbsDecision",
  },
  {
    id: "ads",
    sourceOfTruth: "marketplace_api",
    syncDirection: "marketplace_to_os",
    syncRisk: "medium",
    operationalImportance: "medium",
    overwriteRulesKey: "iready.overwrite.ads",
    navHint: "advertisingPressure",
  },
  {
    id: "reviews",
    sourceOfTruth: "marketplace_api",
    syncDirection: "marketplace_to_os",
    syncRisk: "low",
    operationalImportance: "medium",
    overwriteRulesKey: "iready.overwrite.reviews",
  },
  {
    id: "seo",
    sourceOfTruth: "os_manual",
    syncDirection: "os_to_marketplace",
    syncRisk: "high",
    operationalImportance: "high",
    overwriteRulesKey: "iready.overwrite.seo",
    navHint: "seo",
  },
  {
    id: "prices",
    sourceOfTruth: "shared",
    syncDirection: "bidirectional",
    syncRisk: "critical",
    operationalImportance: "critical",
    overwriteRulesKey: "iready.overwrite.prices",
    navHint: "unitEconomics",
  },
  {
    id: "launches",
    sourceOfTruth: "os_manual",
    syncDirection: "manual_only",
    syncRisk: "high",
    operationalImportance: "critical",
    overwriteRulesKey: "iready.overwrite.launches",
    navHint: "launchOperations",
  },
  {
    id: "supply",
    sourceOfTruth: "os_manual",
    syncDirection: "os_to_marketplace",
    syncRisk: "high",
    operationalImportance: "high",
    overwriteRulesKey: "iready.overwrite.supply",
    navHint: "productionPressure",
  },
  {
    id: "fulfillment",
    sourceOfTruth: "shared",
    syncDirection: "bidirectional",
    syncRisk: "critical",
    operationalImportance: "critical",
    overwriteRulesKey: "iready.overwrite.fulfillment",
    navHint: "fboFbsDecision",
  },
] as const;
